PUT http://localhost:9090/admin/update
content-type: application/json

{
     "id": "",
    "name": "",
    "age": 
    
}


### 
POST http://localhost:9090/admin/create
content-type: application/json

{
    "name": "",
    "country": "",
    "age": 
}

###
GET http://localhost:9090/admin/read



###
DELETE  http://localhost:9090/admin/delete
content-type: application/json

{
    "id": ""
}

