PUT http://localhost:9090/admin/update
content-type: application/json

{
     "id": "",
    "name": "",
    "age": 
    
}


### 
POST http://localhost:9090/admin/create
content-type: application/json

{
    "name": "mario",
    "country": "ola",
    "age": 22
}

###
GET http://localhost:9090/admin/read



###
DELETE  http://localhost:9090/admin/delete
content-type: application/json

{
    "id": "63599da534b3a3e759840000"

}
